// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEC2OT_mkiYHHS15d8YmMP9kyHxZZTGYc',
    appId: '1:548283748086:android:d91e96796fb764eac566d7',
    messagingSenderId: '548283748086',
    projectId: 'conta-em-dia-c954a',
    databaseURL: 'https://conta-em-dia-c954a-default-rtdb.firebaseio.com',
    storageBucket: 'conta-em-dia-c954a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNU9_V6-q26RCcAm2_yf56trFhMNpDyQ',
    appId: '1:548283748086:ios:e62729a6921f66a7c566d7',
    messagingSenderId: '548283748086',
    projectId: 'conta-em-dia-c954a',
    databaseURL: 'https://conta-em-dia-c954a-default-rtdb.firebaseio.com',
    storageBucket: 'conta-em-dia-c954a.firebasestorage.app',
    iosClientId: '548283748086-bsh058lir5ql1ia1gemslfo4l3or25jv.apps.googleusercontent.com',
    iosBundleId: 'br.com.gabrielkozuki.contaemdia',
  );
}
